#!/bin/env python
from queue import Queue, Empty

from monitron.client import ClientThread


if __name__ == '__main__':
    queue = Queue()
    client_thread = ClientThread('localhost', 9988, queue)
    client_thread.start()
    
    while True:
        try:
            print(queue.get(True, 2))
        except Empty:
            pass

    client_thread.join()
